{{- range .Values.storageClasses }}
{{- $shouldCreate := (hasKey . "create" | ternary .create true) }}
{{- if $shouldCreate }}
{{- $name := .name | required "invalid storage class: name is not set" }}
{{- $pool := .storagePool | required "invalid storage class: storage pool is not set"  }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .name | default "lxd-csi" }}
  {{- with .annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
provisioner: lxd.csi.canonical.com
reclaimPolicy: {{ .reclaimPolicy | default "Delete" }}
volumeBindingMode: {{ .volumeBindingMode | default "WaitForFirstConsumer" }}
parameters:
  storagePool: {{ $pool }}
{{- end }}
{{- end }}
