kind: DaemonSet
apiVersion: apps/v1
metadata:
  labels:
    app: lxd-csi-node
  name: lxd-csi-node
  namespace: lxd-csi
spec:
  selector:
    matchLabels:
      app: lxd-csi-node
  template:
    metadata:
      labels:
        app: lxd-csi-node
    spec:
      serviceAccountName: lxd-csi-node-sa
      priorityClassName: system-node-critical
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: node-driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.13.0
          args:
            - --v=2
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path=$(DRIVER_REGISTRATION_SOCKET_PATH)
          env:
            - name: DRIVER_REGISTRATION_SOCKET_PATH
              value: /var/lib/kubelet/plugins/lxd.csi.canonical.com/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            capabilities:
              drop:
                - ALL
        - name: lxd-csi-node
          image: ghcr.io/canonical/lxd-csi:0.0.1
          imagePullPolicy: IfNotPresent
          args:
            - "--node-id=$(NODE_NAME)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--devlxd-endpoint=$(DEVLXD_ENDPOINT)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: DEVLXD_ENDPOINT
              value: unix:///dev/lxd/sock
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: device-dir
              mountPath: /dev
            - name: lxd-mount-dir
              mountPath: /mnt/lxd-csi
              mountPropagation: Bidirectional
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet
              mountPropagation: Bidirectional
            - name: lxd-csi-token
              mountPath: /etc/lxd-csi-driver
              readOnly: true
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            # Privileged is required for bidirectional mount propagation.
            privileged: true
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - SYS_ADMIN
              drop:
                - ALL
      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/lxd.csi.canonical.com
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: lxd-csi-token
          secret:
            secretName: lxd-csi-token
        - name: lxd-mount-dir
          hostPath:
            # CSI requests from LXD to mount filesystem volumes in this directory.
            # When requested, the volume is bind mounted into the pod.
            path: /mnt/lxd-csi
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
            type: Directory
