apiVersion: v2
name: lxd-csi-driver
type: application
description: A Helm chart for LXD CSI driver
home: https://github.com/canonical/lxd-csi-driver

# Both version and appVersion are set to "dev" for development.
# The LXD CSI Driver publishes Helm charts with a matching version of the driver itself.
# The versions are adjusted during the release process and always match, except for the
# latest-edge, where the chart version is always v0-latest-edge to satisfy semver constraint.
version: "v0-dev"
appVersion: "dev"
