name: E2E Test
on:
  pull_request:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: e2e-tests-${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

defaults:
  run:
    # Make sure bash is always invoked with `-eo pipefail`
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    shell: bash

env:
  K8S_CLUSTER_NAME: k8s

jobs:
  e2e-tests:
    runs-on: ubuntu-24.04
    if: ${{ github.event_name != 'schedule' || github.repository == 'canonical/lxd-csi-driver' }}
    strategy:
      fail-fast: false
      matrix:
        storage_driver:
          - dir
          - btrfs
          - zfs
          - lvm
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Install Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: 'go.mod'

      # Build the image before disabling Docker.
      - name: Build CSI driver image
        id: image
        run: |
          set -e
          make image-export
          echo "path=lxd-csi-driver.tar" >> "$GITHUB_OUTPUT"

      # Disable Docker to avoid conflicts with LXD.
      - name: Disable Docker
        uses: canonical/lxd/.github/actions/disable-docker@main

      - name: Install Deps
        run: |
          set -e
          sudo snap install helm --classic
          sudo snap install kubectl --classic

      - name: Setup LXD
        uses: canonical/setup-lxd@main
        with:
          channel: latest/edge

      - name: Set Kubeconfig path
        id: kubeconfig
        run: |
          echo "path=${HOME}/.kube/config" >> "$GITHUB_OUTPUT"

      - name: Deploy Kubernetes cluster
        uses: ./.github/actions/setup-k8s
        with:
          k8s-cluster-name: ${{ env.K8S_CLUSTER_NAME }}
          k8s-node-count: 2
          k8s-snap-channel: latest/edge
          k8s-kubeconfig-path: ${{ steps.kubeconfig.outputs.path }}
          k8s-csi-image-path: ${{ steps.image.outputs.path }}
          k8s-csi-image-tag: dev

      - name: Print cluster info
        run: |
          set -e
          echo "===> Print nodes"
          kubectl get nodes

          echo "===> Print pods"
          kubectl get pods -A

      - name: Run E2E tests
        env:
          TEST_LXD_STORAGE_DRIVERS: "${{ matrix.storage_driver }}"
          K8S_KUBECONFIG_PATH: ${{ steps.kubeconfig.outputs.path }}
        run: |
          set -e
          cd test/e2e
          go install github.com/onsi/ginkgo/v2/ginkgo@$(go list -m -f '{{.Version}}' github.com/onsi/ginkgo/v2)
          ginkgo -v --timeout 60m .
