name: Tests
on:
  pull_request:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: tests-${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

defaults:
  run:
    # Make sure bash is always invoked with `-eo pipefail`
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    shell: bash

jobs:
  code-tests:
    if: ${{ github.event_name != 'schedule' || github.repository == 'canonical/lxd-csi-driver' }}
    name: Code
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: 'go.mod'

      - name: Static analysis
        run:
          set -eu
          make static-analysis

      - name: Go lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0

      - name: Go unit tests
        run: |
          set -eux
          go test -cover ./internal/...

      - name: Helm unit tests
        run: |
          make install-helm
          helm unittest charts/
